### ISSUE TITLE
Demonstration

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#1]
Show the remaining components!

**Comment by punisha1996** [comment]
10pcs L78S05CV TO-220 78S05 TO2205V 2A L78S05, NEO-6M GPS Module with Antenna ,Heart Rate Pulse Sensor Sensor Module, Li ion Battery 3.7v 3000mAh Rechargeable Lithium Battery,  ESP32-CAM Wi-Fi Bluetooth, 4G 3G GNSS HAT Based on SIM7600A-H LTE CAT4 150Mbps Wireless Communication (GSM),-----it shows arrival by the end of the month.

**Comment by punisha1996** [comment]
Raspberry Pi 4, ADXL345 3-Axis Digital Accelerometer Module ,PC817C Optocoupler Photocoupler ------arrive by 18 june -20 june.

**Comment by punisha1996** [comment]
I have received raspberry  pi4 yesterday. and the other components are on its way .10pcs L78S05CV TO-220 78S05 TO2205V 2A L78S05, NEO-6M GPS Module with Antenna ,Heart Rate Pulse Sensor Sensor Module, Li ion Battery 3.7v 3000mAh Rechargeable Lithium Battery, ESP32-CAM Wi-Fi Bluetooth, 4G 3G GNSS HAT Based on SIM7600A-H LTE CAT4 150Mbps Wireless Communication (GSM),-----it shows arrival by the end of the month.

**Comment by punisha1996** [comment]
ADXL345 3-Axis Digital Accelerometer Module ,PC817C Optocoupler Photocoupler ------arrive by  in between 19june -29 june.

**Comment by punisha1996** [comment]
just now I have received ADXL345 3-Axis Digital Accelerometer Module ,PC817C Optocoupler Photocoupler.

**Comment by mikeshams** [comment]
So, ESP 32, GSM, GPS, Pulse rate sensor, batteries, and regulators are still left.

**Comment by punisha1996** [comment]
just now I have received ESP 32  and regulators. GPS, Pulse rate sensor, batteries and GSM  are still left.

**Comment by mikeshams** [comment]
I have updated the milestone.

**Comment by punisha1996** [comment]
i have received NEO-6M GPS,Pulse Rate Sensor and batteries. GSM is still left.

**Comment by punisha1996** [comment]
i have received batteries.

**Comment by mikeshams** [comment]
So GPS,GSM,PULSE RATE SENSOR are still remaining!

**Comment by punisha1996** [comment]
i have received Pulse Rate Sensor.

**Comment by punisha1996** [comment]
We have received GPS and GSM. Veerpal is testing them.
