### ISSUE TITLE
Power Management (2)

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#10]
How to manage the power consumption for the MCU in terms of software?

**Comment by SIMKY169** [comment]
Well, in terms of software for the MCU the sleepy pi(command) shut down the raspberry pi . Hence, Raspbian (operating system) goes shut down. when it detects sleepy pi, OS does not run . Therefore, raspberry pi goes into a low power mode leading to manage power. However, in my project, it is not possible to implement the above-mentioned as most of the components are getting power externally such as Raspberry pi, ADXL 345, and temperature sensor. And we (Group 4) cannot put an external power device into the sleep mode. Also, our project is working in the parallel mode so let's suppose if some kind of input gets generated from ADXL 345 Or any other component, just imagine at the same time Raspberry pi will turn into sleep mode then how it can be ensured the old (sufferer) fall or not oR get assistance or not in a timely manner.
