### ISSUE TITLE
ESP 32 cam

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#11]
You can go with pi camera or use another type of ESP 32 CAM in general speaking.
If you insist on using ESP 32 then ensuring wifi connection is important while uploading code into it.
1. Find a proper solution 
2. Revise your ppt file
3. Demonstrate it!

**Comment by SIMKY169** [comment]
Fortunately, it worked for me by changing the configuration, I have revised my ppt as well. 
[3rd meeting DONE.pptx](https://github.com/navjotsb/CapstoneProject_G4/files/6902367/3rd.meeting.DONE.pptx)
I am ready to demonstrate.
