### ISSUE TITLE
Real Time Operation

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#12]
Review the two following links and if you get new idea for this task then modify your ppt file and the way you want to demonstrate it!
1. https://all3dp.com/2/rtos-raspberry-pi-real-time-os/

2. https://www.geeksforgeeks.org/priority-queue-in-python/

**Comment by V1205903** [comment]
I am working on it, sir.

**Comment by V1205903** [comment]
I have uploaded New ppt and Code in the main branch with the names **Veerpal 4th Individual meeting.pptx and Veerpal 4th IM Final Code.**
1> https://github.com/navjotsb/CapstoneProject_G4/blob/main/Veerpal%204th%20IM%20Final%20Code
2> https://github.com/navjotsb/CapstoneProject_G4/blob/main/Veerpal%204th%20Individual%20meeting.pptx

**Comment by V1205903** [comment]
The reference has been added(1st one) and the main things have been added such as output.
Thank you Sir.
