### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#2]
Add the description in detain of your capstone project in the repository!

**Comment by SIMKY169** [comment]
[git 1.docx](https://github.com/navjotsb/CapstoneProject_G4/files/6634542/git.1.docx)

**Comment by navjotsb** [comment]
She has uploaded it. Please check under the main branch.

**Comment by SIMKY169** [comment]
i have uploaded it in main branch in a folder
