### ISSUE TITLE
Testing Components Part 1

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#4]
Test the following components correctly:
1. Accelerometer
2. Temperature Sensor
3. Pulse Rate Sensor

**Comment by Sukh-star** [comment]
sir, I have tested my accelerometer and it's working fine now. Can I demonstrate the testing in class?

**Comment by mikeshams** [comment]
A. Test the following components correctly:
1. Temperature Sensor
2. Pulse Rate Sensor

B. Regarding x, y, z for the accelerometer, what do they represent for? Why did you use m/s^2?

**Comment by Sukh-star** [comment]
As the accelerometer measures acceleration, which is the change in an object's velocity per second.
velocity= meter/second
So, Acceleration = velocity/second
= meter/second/second
=meter/second square
so, I use the m/s^2 unit for acceleration

**Comment by Sukh-star** [comment]
The X, Y, and Z accelerations are all vectors points that are defined along a specific axis. Those axes have clearly defined positive and negative directions. For example, when you look at your phone's screen, positive Y is up, negative Y is down, positive X is to the right, and negative X is to the left. Individually, these values can be either positive or negative where "positive" means that the vector points in the positive direction, and "negative" means that the vector points in the negative direction.

**Comment by Sukh-star** [comment]
I have received a pulse rate sensor and a new temperature sensor and successfully tested them. Can I test them in class today?
