### ISSUE TITLE
Testing Components

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#5]
Demonstrate testing GPS and GSM modules!

**Comment by V1205903** [comment]
I got the components. Testing of GSM is done and I am ready to share my testing information. GPS is not working as it should work. I have a doubt about it.

**Comment by mikeshams** [comment]
Please let me know when the GPS is tested successfully

**Comment by V1205903** [comment]
Sir as mentioned the delivery of GPS is on 20th May, But I am expecting it within 2 days. As I got the notification parcel was scanned in Brampton. I would appreciate the chance to show testing on Thursday most probably or Monday(if I do not get delivery).

**Comment by mikeshams** [comment]
Demonstrate testing of GPS this Wednesday!

**Comment by V1205903** [comment]
I have received and tested GPS Module, and I am ready to test it in class as well.
