### ISSUE TITLE
Buzzer Interfacing

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#6]
1. Modify your references in APA style
2. Explain how to change the way the buzzer beeps

**Comment by punisha1996** [comment]
[INTERFACING OF RASBERRY PI 4 WITH BUZZER.pptx](https://github.com/navjotsb/CapstoneProject_G4/files/6766431/INTERFACING.OF.RASBERRY.PI.4.WITH.BUZZER.pptx)
i have updated my file.

**Comment by punisha1996** [comment]
We can change the beep of buzzer by adding multiple line of Buzzer on and off with random time delay.
code:-
#include <iostream>
#include <wiringPi.h>
#include <stdlib.h>
#include <time.h>

using namespace std;

int pinNumber=2;
int randomTime;

int main(){

    wiringPiSetupGpio();
    pinMode(pinNumber, OUTPUT);
	while (1){
        randomTime = (rand() % (1000 - 50 + 1)) + 50;
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        delay(randomTime);
	randomTime = (rand() % (500 - 150 + 1)) + 150;
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        
        digitalWrite(pinNumber, HIGH);	/* write HIGH on GPIO */
        delay(randomTime);
	randomTime = (rand() % (2000 - 550 + 1)) + 550;
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        delay(randomTime);
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        randomTime = (rand() % (750 - 250 + 1)) + 250;
        digitalWrite(pinNumber, HIGH);	/* write HIGH on GPIO */
        delay(randomTime);
	
        randomTime = (rand() % (1000 - 50 + 1)) + 50;
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        delay(randomTime);
	randomTime = (rand() % (500 - 150 + 1)) + 150;
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        
        digitalWrite(pinNumber, HIGH);	/* write HIGH on GPIO */
        delay(randomTime);
	randomTime = (rand() % (2000 - 550 + 1)) + 550;
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        delay(randomTime);
        digitalWrite(pinNumber,LOW);		/* write LOW on GPIO */
        randomTime = (rand() % (750 - 250 + 1)) + 250;
        digitalWrite(pinNumber, HIGH);	/* write HIGH on GPIO */
        delay(randomTime);
	}
    return 0;
}

**Comment by punisha1996** [comment]
second example:-
#include <wiringPi.h> /* include wiringPi library */
#include <stdio.h>    
#include <softPwm.h>  /* include header file for software PWM */

int main(){
	int PWM_pin = 2;		/* GPIO1 as per WiringPi,GPIO18 as per BCM */
	int intensity;
	wiringPiSetupGpio();		/* initialize wiringPi setup */
	pinMode(PWM_pin,OUTPUT);	/* set GPIO as output */
	softPwmCreate(PWM_pin,1,100);	/* set PWM channel along with range*/
	while (1)
	  {
		for (intensity = 0; intensity < 101; intensity++)
		{
		  softPwmWrite (PWM_pin, intensity); /* change the value of PWM */
		  delay (10) ;
		}
		delay(1);

		for (intensity = 100; intensity >= 0; intensity--)
		{
		  softPwmWrite (PWM_pin, intensity);
		  delay (10);
		}
		delay(1);
		
	}
}
