### ISSUE TITLE
Pulse Rate Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [navjotsb/CapstoneProject_G4#9]
The output results should be stable

**Comment by Sukh-star** [comment]
sir i am working on the code. the components were busy with simky before for esp32 interfacing. i will update soon about this issue.

**Comment by mikeshams** [comment]
ok

**Comment by Sukh-star** [comment]
Sir, I have done my task and the output is stable now. can I demonstrate in the upcoming class?

**Comment by Sukh-star** [comment]
I have also uploaded the ppt file with the new code on moodle as well sent you the ppt through the mail.
